---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres
  annotations:
    a8r.io/description: "Credentials for postgres superuser"
stringData:
  POSTGRES_USER: ...
  POSTGRES_PASSWORD: ...