---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: hpc-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: dpage/pgadmin4:latest
        imagePullPolicy: Always
        name: pgadmin
        envFrom:
          - secretRef:
              name: proxy-secret
          - configMapRef:
              name: pgadmin-configmap
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 516Mi
      restartPolicy: Always
      serviceAccountName: sa-pgadmin
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        allowPriviligeEscalation: true
