---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pgadmin
  namespace: hpc-services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /pgadmin
            backend:
              serviceName: pgadmin
              servicePort: 80