---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pgadmin-nginx
  namespace: hpc-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-pgadmin-nginx-role
  namespace: hpc-services
rules:
  - apiGroups: [ policy ]
    resources: [ podsecuritypolicies ]
    verbs: [ use ]
    resourceNames: [ privileged ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-pgadmin-nginx-role-binding
  namespace: hpc-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-pgadmin-nginx-role
subjects:
  - kind: ServiceAccount
    name: sa-pgadmin-nginx
    namespace: hpc-services
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-nginx-conf
  namespace: hpc-services
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  _;
        absolute_redirect off;

        location /pgadmin4/ {
          proxy_set_header X-Script-Name /pgadmin4;
          proxy_set_header Host $http_host;
          proxy_pass http://pgadmin;
          proxy_redirect off;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-nginx
  namespace: hpc-services
spec:
  selector:
    matchLabels:
      run: pgadmin-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: pgadmin-nginx
    spec:
      containers:
        - name: pgadmin-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pgadmin-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      serviceAccountName: sa-pgadmin-nginx
      volumes:
        - name: pgadmin-nginx-conf
          configMap:
            name: pgadmin-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-nginx
  namespace: hpc-services
  labels:
    run: pgadmin-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: pgadmin-nginx