---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hpc-services
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: true
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - ALL
 volumes:
    - configMap
    - secret
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - persistentVolumeClaim
hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: RunAsAny
    ranges:
      - min: 0
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 0
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 0
        max: 65535
  runAsGroup:
    ranges:
    - max: 65535
      min: 500
    rule: MustRunAs
  readOnlyRootFilesystem: false
