---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: hpc-services
spec:

  selector:
    app: pgadmin

  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP