---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: buildkite-agent
stringData:

  # The Buildkite token
  BUILDKITE_AGENT_TOKEN: ...

  # Authorized team to use the agent
  ALLOWED_BUILDKITE_TEAM: everyone