---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: hpc-services

spec:

  replicas: 3
  image: postgres:latest
  port: 5432

  database:
    size: 200Mi
    storageClassName: standard
    volumeMount: /var/lib/postgresql/data

  envFrom:
    - secretRef:
        name: postgres-secret