---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: ha-postgres
  namespace: hpc-services

spec:

  version: 13.2
  replicas: 3

  standbyMode: Hot # enable load balancing
  streamingMode: Asynchronous # only supported mode

  # 'postgres' db credentials
  authSecret:
    name: pgauth-secret

  # pvc parameters
  storageType: Durable
  storage:
    storageClassName: standard
    accessModes: [ ReadWriteOnce ]
    resources:
      requests:
        storage: 1Gi

  # enable builtin prometheus monitoring
  monitor:
    agent: prometheus.io/builtin

  podTemplate:
    metadata:
      annotations: # pod's annotations
        version: 13.2
        a8r:io/documentation: https://kubedb.com/docs/v2021.06.23/guides/postgres
    controller:
      annotations:
        a8r:io/documentation: https://kubedb.com/docs/v2021.06.23/guides/postgres
    spec:
      serviceAccountName: sa-postgres
      resources:
        requests:
          memory: 64Mi
          cpu: 250m
        limits:
          memory: 128Mi
          cpu: 500m

  serviceTemplate:
    - alias: primary
      metadata:
        annotations:
          a8r:io/documentation: https://kubedb.com/docs/v2021.06.23/guides/postgres
      spec:
        type: NodePort
        ports:
          - name: http
            port: 5432
    - alias: standby
      metadata:
        annotations:
          a8r:io/documentation: https://kubedb.com/docs/v2021.06.23/guides/postgres
      spec:
        type: NodePort
        ports:
          - name: http
            port: 5432

  # prevent db deletion if crd is deleted
  terminationPolicy: DoNotTerminate