---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: hpc-services

spec:

  replicas: 3
  image: postgres:latest
  port: 5432

  database:
    size: 200Mi
    storageClassName: standard
    volumeMount: /var/lib/postgresql/data

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: postgres-password

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: postgres-replication-password