---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: ha-postgres
  namespace: hpc-services

spec:

  version: 13.2
  replicas: 3

  standbyMode: Hot # enable load balancing
  streamingMode: Asynchronous # only supported mode

  # 'postgres' db credentials
  authSecret:
    name: p1-auth

  # pvc parameters
  storageType: Durable
  storage:
    storageClassName: standard
    accessModes: [ ReadWriteOnce ]
    resources:
      requests:
        storage: 1Gi

  # enable builtin prometheus monitoring
  monitor:
    agent: prometheus.io/builtin

  podTemplate:
    metadata:
      annotations: # pod's annotations
        version: 13.2
    controller:
      annotations: # statefulSet's annotations
        version: 13.2
    spec:
      serviceAccountName: sa-postgres
      resources:
        requests:
          memory: 64Mi
          cpu: 250m
        limits:
          memory: 128Mi
          cpu: 500m