---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: ha-postgres

spec:

  replicas: 3
  image: postgres:latest
  port: 5432

  database:
    size: 200Mi
    storageClassName: standard
    volumeMount: /var/lib/postgresql/data

  env:
    # password for superuser 'postgres'
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD

    # password for user 'replication'
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_REPLICATION_PASSWORD