---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: ha-postgres

spec:

  version: "13.2"
  replicas: 3

  standbyMode: Hot # enable load balancing
  streamingMode: Asynchronous # only supported mode

  # postgres admin credentials
  authSecret:
    name: ha-postgres

  # pvc parameters
  storageType: Durable
  storage:
    storageClassName: standard
    accessModes: [ ReadWriteOnce ]
    resources:
      requests:
        storage: 1Gi

  podTemplate:
    metadata:
      annotations: # pod's annotations
        version: "13.2"
        a8r.io/documentation: "https://kubedb.com/docs/v2021.06.23/guides/postgres"
    controller:
      annotations:
        a8r.io/documentation: "https://kubedb.com/docs/v2021.06.23/guides/postgres"
    spec:
      serviceAccountName: ha-postgres
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m

  serviceTemplate:
    - alias: primary
      metadata:
        annotations:
          a8r.io/documentation: "https://kubedb.com/docs/v2021.06.23/guides/postgres"
      spec:
        type: NodePort
        ports:
          - name: http
            port: 5432
    - alias: standby
      metadata:
        annotations:
          a8r.io/documentation: "https://kubedb.com/docs/v2021.06.23/guides/postgres"
      spec:
        type: NodePort
        ports:
          - name: http
            port: 5432

  terminationPolicy: Halt