---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: postgres
  annotations:
    kubernetes.io/description: 'psp for postgres database'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false

  allowedCapabilities: [ ]
  requiredDropCapabilities: [ ALL ]
  defaultAddCapabilities: [ ]

  hostNetwork: false
  hostIPC: false
  hostPID: false

  seLinux:
    rule: RunAsAny

  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - persistentVolumeClaim
    - emptyDir
    - secret
  readOnlyRootFilesystem: false
