---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
  annotations:
    a8r.io/description: "A postgres database"
    a8r.io/owner: renatodamas

spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: chmod-pgdata
          image: postgres:latest
          command: [ "chown", "-R", "1000", "/var/lib/pgsql/data" ]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add: [ CHOWN ]
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data
              readOnly: false
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: proxy
            - secretRef:
                name: postgres
          env:
            - name: PGDATA
              value: /var/lib/pgsql/data
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data
              readOnly: false
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      serviceAccountName: postgres
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: pgdata
        annotations:
          volume.beta.kubernetes.io/storage-class: default
      spec:
        storageClassName: default
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 5Gi
