---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services

resources:
  - ns.yaml
  - ../../base/
  - secrets/sealed/
  - ../../components/buildkite-agent/.kustomization/overlays/prd/
  - ../../components/portal-service/.kustomization/overlays/prd/
  - ../../components/ticket-service/.kustomization/overlays/prd/

components:
  - ../../components/postgres/
