---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: buildkite-agent
  annotations:
    kubernetes.io/description: 'psp for buildkite agent pod'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
spec:
  privileged: false # prevent creation of privileged Pods

  allowPrivilegeEscalation: false # prevent setuid

  allowedCapabilities: [ ]           # no additional capabilities required
  requiredDropCapabilities: [ ]      # keep default capabilities
  defaultAddCapabilities: [ ]        # keep default capabilities

  hostNetwork: false    # disallow host networking
  hostIPC: false        # disallow sharing the IPC hostname
  hostPID: false        # disallow sharing the host process ID namespace

  seLinux: # harness for SELinux
    rule: RunAsAny

  runAsUser: # require the container to run without root privileges
    rule: MustRunAsNonRoot
  runAsGroup: # forbid adding the root group
    ranges:
      - min: 1000
        max: 65535
    rule: MustRunAs
  supplementalGroups: # forbid adding the root group
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 65535
  fsGroup: # forbid adding the root group
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 65535
  volumes: # allow only these volume types
    - configMap
    - secret
    - persistentVolumeClaim
  readOnlyRootFilesystem: false
