---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildkite-agent
  namespace: hpc-services
rules:
  - apiGroups: [ policy ]
    resources: [ podsecuritypolicies ]
    verbs: [ use ]
    resourceNames: [ buildkite-agent ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildkite-agent
  namespace: hpc-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildkite-agent
subjects:
  - kind: ServiceAccount
    name: sa-buildkite-agent
    namespace: hpc-services
