---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: buildkite-agent
  namespace: hpc-services
stringData:

  # The Buildkite token
  BUILDKITE_AGENT_TOKEN: ...

  # Database settings
  PGUSER: ...
  PGPASSWORD: ...
  PGHOST: ha-postgres
  PGPORT: "5432"
  PGDATABASE: buildkite-agent