---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgadmin-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  _;
        absolute_redirect off;

        location /pgadmin4/ {
          proxy_set_header X-Script-Name /pgadmin4;
          proxy_set_header Host $http_host;
          proxy_pass http://pgadmin;
          proxy_redirect off;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-nginx
spec:
  selector:
    matchLabels:
      run: pgadmin-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: pgadmin-nginx
    spec:
      containers:
        - name: pgadmin-nginx
          image: nginxinc/nginx-unprivileged
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: pgadmin-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      serviceAccountName: pgadmin-nginx
      volumes:
        - name: pgadmin-nginx-conf
          configMap:
            name: pgadmin-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-nginx
  labels:
    run: pgadmin-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: pgadmin-nginx