---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgadmin
rules:
  - apiGroups: [ policy ]
    resources: [ podsecuritypolicies ]
    verbs: [ use ]
    resourceNames: [ pgadmin-psp ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pgadmin
subjects:
  - kind: ServiceAccount
    name: pgadmin