---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildkite-agent
rules:
  - apiGroups: [ policy ]
    resources: [ podsecuritypolicies ]
    verbs: [ use ]
    resourceNames: [ privileged-buildkite-agent ]