---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ticket-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
      http:
        paths:
          - path: /api/ticket
            pathType: Prefix
            backend:
              service:
                name: ticket-api
                port:
                  number: 80